// Generated by app/scripts/generate-lessons.mjs. Do not edit manually.
export type Level = "Beginner" | "Intermediate" | "Advanced";
export type Lesson = { id: string; level: Level; step: string; title: string; summary: string; readme: string; lab: string; notebook: string };
export const lessons: Lesson[] = [
  {
    "id": "beginner-01",
    "level": "Beginner",
    "step": "01",
    "title": "MCP Architecture, Lifecycle, and Trust Boundaries",
    "summary": "After this course, you can trace a Model Context Protocol (MCP) session from connection through shutdown; distinguish host, client, server, tool, resource, and prompt responsibilities; identify the principal, authority, data, logging, failure, and revocation path at every boundary; and reject the mistake of treating a discovered capability or natural-language description as permission.",
    "readme": "curriculum/beginner/01-mcp-architecture-lifecycle-trust-boundaries/README.md",
    "lab": "curriculum/beginner/01-mcp-architecture-lifecycle-trust-boundaries/lab.py",
    "notebook": "curriculum/beginner/01-mcp-architecture-lifecycle-trust-boundaries/mcp_architecture_lifecycle.ipynb"
  },
  {
    "id": "beginner-02",
    "level": "Beginner",
    "step": "02",
    "title": "Threat Modeling MCP and Agent Protocol Systems",
    "summary": "Build a data-flow diagram for an MCP integration; name assets, principals, boundaries, and assumptions; use STRIDE, attack trees, misuse cases, and security invariants; and turn every material threat into a control, executable test, telemetry signal, incident action, and accepted residual-risk decision.",
    "readme": "curriculum/beginner/02-threat-modeling-mcp-agent-protocols/README.md",
    "lab": "curriculum/beginner/02-threat-modeling-mcp-agent-protocols/lab.py",
    "notebook": "curriculum/beginner/02-threat-modeling-mcp-agent-protocols/mcp_threat_modeling.ipynb"
  },
  {
    "id": "beginner-03",
    "level": "Beginner",
    "step": "03",
    "title": "Secure Tool, Resource, and Prompt Interface Design",
    "summary": "Design narrow MCP tools with typed schemas and semantic validation; distinguish read and proposed-write operations; scope resources by URI, tenant, ownership, freshness, and classification; and treat server-provided prompts and all untrusted MCP content as configuration or data—not as instructions with authority.",
    "readme": "curriculum/beginner/03-secure-tool-resource-prompt-interfaces/README.md",
    "lab": "curriculum/beginner/03-secure-tool-resource-prompt-interfaces/lab.py",
    "notebook": "curriculum/beginner/03-secure-tool-resource-prompt-interfaces/secure_interfaces.ipynb"
  },
  {
    "id": "beginner-04",
    "level": "Beginner",
    "step": "04",
    "title": "Building a Minimal Secure MCP Server",
    "summary": "Build and inspect a real MCP server with the official Python SDK; expose a resource, prompt, two read-only tools, and a proposed side-effect tool; use typed interfaces, stable IDs, structured denials, approval binding, and security-relevant logs; and explain which controls this baseline deliberately defers to later identity, policy, isolation, and supply-chain courses.",
    "readme": "curriculum/beginner/04-minimal-secure-mcp-server/README.md",
    "lab": "curriculum/beginner/04-minimal-secure-mcp-server/lab.py",
    "notebook": "curriculum/beginner/04-minimal-secure-mcp-server/minimal_secure_server.ipynb"
  },
  {
    "id": "beginner-05",
    "level": "Beginner",
    "step": "05",
    "title": "MCP Client/Host Security and Capability Negotiation",
    "summary": "Review a server before connection and after capability discovery; distinguish trusted server identity from untrusted server metadata; bind a capability cache to identity, version, and artifact digest; filter risky tools/resources/prompts; and revoke a server so new sessions and cached capabilities are denied.",
    "readme": "curriculum/beginner/05-client-host-security-capability-negotiation/README.md",
    "lab": "curriculum/beginner/05-client-host-security-capability-negotiation/lab.py",
    "notebook": "curriculum/beginner/05-client-host-security-capability-negotiation/capability_negotiation.ipynb"
  },
  {
    "id": "intermediate-06",
    "level": "Intermediate",
    "step": "06",
    "title": "MCP Authentication and OAuth Security",
    "summary": "Validate a token's issuer, audience, expiry, scopes, and revocation state; separate OAuth authentication from authorization; explain authorization server, resource server, client, and resource owner roles; and reject token passthrough and confused-audience patterns in MCP integrations.",
    "readme": "curriculum/intermediate/06-mcp-authentication-oauth-security/README.md",
    "lab": "curriculum/intermediate/06-mcp-authentication-oauth-security/lab.py",
    "notebook": "curriculum/intermediate/06-mcp-authentication-oauth-security/oauth_security.ipynb"
  },
  {
    "id": "intermediate-07",
    "level": "Intermediate",
    "step": "07",
    "title": "Authorization and Policy Enforcement",
    "summary": "Evaluate a decision over principal, action, resource, tenant, purpose, risk, and approval; compare RBAC, ABAC, and relationship-based authorization; and enforce denial at a tool/API boundary outside the model.",
    "readme": "curriculum/intermediate/07-authorization-policy-enforcement/README.md",
    "lab": "curriculum/intermediate/07-authorization-policy-enforcement/lab.py",
    "notebook": "curriculum/intermediate/07-authorization-policy-enforcement/policy_enforcement.ipynb"
  },
  {
    "id": "intermediate-08",
    "level": "Intermediate",
    "step": "08",
    "title": "Delegation, Token Exchange, and Confused Deputy",
    "summary": "Trace authority from user to agent to MCP server to downstream API; exchange a parent grant for a strictly narrower child grant; enforce audience, tenant, resource, action, purpose, expiry, and maximum depth; and detect a confused deputy before a privileged server accesses another caller's data.",
    "readme": "curriculum/intermediate/08-delegation-token-exchange-confused-deputy/README.md",
    "lab": "curriculum/intermediate/08-delegation-token-exchange-confused-deputy/lab.py",
    "notebook": "curriculum/intermediate/08-delegation-token-exchange-confused-deputy/delegation_security.ipynb"
  },
  {
    "id": "intermediate-09",
    "level": "Intermediate",
    "step": "09",
    "title": "Runtime Isolation and Sandboxing",
    "summary": "Define a sandbox boundary for a local or remote MCP server; constrain filesystem, process, environment, network, and identity; distinguish policy simulation from enforcement; and collect evidence for a denied escape attempt.",
    "readme": "curriculum/intermediate/09-runtime-isolation-sandboxing/README.md",
    "lab": "curriculum/intermediate/09-runtime-isolation-sandboxing/lab.py",
    "notebook": "curriculum/intermediate/09-runtime-isolation-sandboxing/runtime_isolation.ipynb"
  },
  {
    "id": "intermediate-10",
    "level": "Intermediate",
    "step": "10",
    "title": "Filesystem, Network, SSRF, and Egress Security",
    "summary": "Constrain file access and outbound network calls; recognize SSRF through cloud metadata, private ranges, redirects, DNS rebinding, and URL parsing confusion; and verify egress at the network boundary rather than trusting a model-selected URL or an application allow-list alone.",
    "readme": "curriculum/intermediate/10-filesystem-network-ssrf-egress-security/README.md",
    "lab": "curriculum/intermediate/10-filesystem-network-ssrf-egress-security/lab.py",
    "notebook": "curriculum/intermediate/10-filesystem-network-ssrf-egress-security/egress_security.ipynb"
  },
  {
    "id": "intermediate-11",
    "level": "Intermediate",
    "step": "11",
    "title": "Prompt Injection, Tool Poisoning, and Untrusted MCP Content",
    "summary": "Treat tool descriptions, prompt templates, resources, results, and external documents as untrusted content; detect risk signals without granting authority; and require independent authorization, validation, and approval before a model can take a new action influenced by that content.",
    "readme": "curriculum/intermediate/11-prompt-injection-tool-poisoning-untrusted-content/README.md",
    "lab": "curriculum/intermediate/11-prompt-injection-tool-poisoning-untrusted-content/lab.py",
    "notebook": "curriculum/intermediate/11-prompt-injection-tool-poisoning-untrusted-content/untrusted_content.ipynb"
  },
  {
    "id": "intermediate-12",
    "level": "Intermediate",
    "step": "12",
    "title": "Supply-Chain Provenance, SBOMs, Signing, and Dependencies",
    "summary": "Verify an immutable server artifact; distinguish integrity, provenance, and vulnerability evidence; generate and use SBOM inventory; enforce trusted build provenance; and reject a signed artifact when its release evidence is incomplete or unacceptable.",
    "readme": "curriculum/intermediate/12-supply-chain-provenance-sbom-signing-dependencies/README.md",
    "lab": "curriculum/intermediate/12-supply-chain-provenance-sbom-signing-dependencies/lab.py",
    "notebook": "curriculum/intermediate/12-supply-chain-provenance-sbom-signing-dependencies/provenance_gate.ipynb"
  },
  {
    "id": "intermediate-13",
    "level": "Intermediate",
    "step": "13",
    "title": "Secure MCP CI/CD and Release Gates",
    "summary": "Design a promotion pipeline that produces and verifies tests, provenance, SBOM, vulnerability, policy, deployment, and rollback evidence; and reject manual or model-generated claims that are not attached to an immutable artifact.",
    "readme": "curriculum/intermediate/13-secure-mcp-cicd-release-gates/README.md",
    "lab": "curriculum/intermediate/13-secure-mcp-cicd-release-gates/lab.py",
    "notebook": "curriculum/intermediate/13-secure-mcp-cicd-release-gates/release_gates.ipynb"
  },
  {
    "id": "advanced-14",
    "level": "Advanced",
    "step": "14",
    "title": "MCP Security Testing and Fuzzing",
    "summary": "Turn MCP security invariants into deterministic tests; build negative contract, parser, schema, resource, and capability cases; use bounded fuzzing/mutation to find unexpected accepts; and preserve failures as regression fixtures.",
    "readme": "curriculum/advanced/14-mcp-security-testing-fuzzing/README.md",
    "lab": "curriculum/advanced/14-mcp-security-testing-fuzzing/lab.py",
    "notebook": "curriculum/advanced/14-mcp-security-testing-fuzzing/security_testing.ipynb"
  },
  {
    "id": "advanced-15",
    "level": "Advanced",
    "step": "15",
    "title": "MCP Red Teaming and Adversarial Evaluation",
    "summary": "Plan authorized red-team campaigns against MCP host, client, server, tool, resource, prompt, identity, registry, and supply-chain boundaries; measure attack success, detection, containment, and safe completion; and convert each finding into a reproducible regression test and owned remediation.",
    "readme": "curriculum/advanced/15-mcp-red-teaming-adversarial-evaluation/README.md",
    "lab": "curriculum/advanced/15-mcp-red-teaming-adversarial-evaluation/lab.py",
    "notebook": "curriculum/advanced/15-mcp-red-teaming-adversarial-evaluation/red_team_evaluation.ipynb"
  },
  {
    "id": "advanced-16",
    "level": "Advanced",
    "step": "16",
    "title": "MCP Runtime Observability and Continuous Assurance",
    "summary": "Define security-relevant MCP traces; correlate artifact identity, session, principal/tenant, capability, tool/resource, destination, policy decision, and result; detect behavioral drift; and route signals to bounded controls without granting new authority.",
    "readme": "curriculum/advanced/16-runtime-observability-continuous-assurance/README.md",
    "lab": "curriculum/advanced/16-runtime-observability-continuous-assurance/lab.py",
    "notebook": "curriculum/advanced/16-runtime-observability-continuous-assurance/runtime_assurance.ipynb"
  },
  {
    "id": "advanced-17",
    "level": "Advanced",
    "step": "17",
    "title": "MCP Server Registry, Discovery, Trust, and Enterprise Gateways",
    "summary": "Design a server onboarding record; separate discovery from enablement; bind identity, owner, endpoint/launch specification, artifact digest, capabilities, review, and revocation; and use an enterprise gateway as a policy/observability point without assuming it removes server-side controls.",
    "readme": "curriculum/advanced/17-server-registry-discovery-trust-enterprise-gateways/README.md",
    "lab": "curriculum/advanced/17-server-registry-discovery-trust-enterprise-gateways/lab.py",
    "notebook": "curriculum/advanced/17-server-registry-discovery-trust-enterprise-gateways/registry_trust.ipynb"
  },
  {
    "id": "advanced-18",
    "level": "Advanced",
    "step": "18",
    "title": "Agent-to-Agent / A2A Security and Delegation",
    "summary": "Authenticate agent peers, authorize a bounded task rather than a broad agent, preserve tenant/purpose/trace linkage, limit lifetime and hops, and prevent a downstream agent from treating a peer request as unrestricted authority.",
    "readme": "curriculum/advanced/18-agent-to-agent-a2a-security-delegation/README.md",
    "lab": "curriculum/advanced/18-agent-to-agent-a2a-security-delegation/lab.py",
    "notebook": "curriculum/advanced/18-agent-to-agent-a2a-security-delegation/a2a_security.ipynb"
  },
  {
    "id": "advanced-19",
    "level": "Advanced",
    "step": "19",
    "title": "Protocol Composition Security: MCP + A2A + Agent Runtimes",
    "summary": "Identify security-context loss at protocol adapters; preserve authenticated subject, tenant, action, resource/purpose, audience, expiry, approval, trace, and error semantics; and reject an adapter that broadens authority or silently converts a denial into a retry/allow.",
    "readme": "curriculum/advanced/19-protocol-composition-security/README.md",
    "lab": "curriculum/advanced/19-protocol-composition-security/lab.py",
    "notebook": "curriculum/advanced/19-protocol-composition-security/protocol_composition.ipynb"
  },
  {
    "id": "advanced-20",
    "level": "Advanced",
    "step": "20",
    "title": "Multi-Agent and Cross-Server Attack Paths",
    "summary": "Model lateral movement across hosts, agents, MCP servers, registries, gateways, and downstream APIs; identify transitive authority; calculate bounded reachability; and place controls that reduce blast radius and support containment.",
    "readme": "curriculum/advanced/20-multi-agent-cross-server-attack-paths/README.md",
    "lab": "curriculum/advanced/20-multi-agent-cross-server-attack-paths/lab.py",
    "notebook": "curriculum/advanced/20-multi-agent-cross-server-attack-paths/attack_paths.ipynb"
  },
  {
    "id": "advanced-21",
    "level": "Advanced",
    "step": "21",
    "title": "MCP Incident Detection, Containment, and Forensics",
    "summary": "Detect suspicious server behavior; contain it through server, session, credential, and network controls; preserve redacted, integrity-protected evidence; scope affected users/artifacts; and coordinate recovery without destroying the forensic record.",
    "readme": "curriculum/advanced/21-incident-detection-containment-forensics/README.md",
    "lab": "curriculum/advanced/21-incident-detection-containment-forensics/lab.py",
    "notebook": "curriculum/advanced/21-incident-detection-containment-forensics/incident_forensics.ipynb"
  },
  {
    "id": "advanced-22",
    "level": "Advanced",
    "step": "22",
    "title": "Recovery, Revocation, Rollback, and Resilience",
    "summary": "Recover an MCP service to verified known-good bytes; propagate revocation across registry, host cache, sessions, credentials, and network; distinguish rollback from root-cause eradication; and test resilience under partial failure.",
    "readme": "curriculum/advanced/22-recovery-revocation-rollback-resilience/README.md",
    "lab": "curriculum/advanced/22-recovery-revocation-rollback-resilience/lab.py",
    "notebook": "curriculum/advanced/22-recovery-revocation-rollback-resilience/recovery_resilience.ipynb"
  },
  {
    "id": "advanced-23",
    "level": "Advanced",
    "step": "23",
    "title": "Enterprise MCP Security Architecture",
    "summary": "Design a platform architecture with distinct registry, identity, authorization, isolation, observability, revocation, and tenant-boundary controls; assign owners; and review cross-plane failure and bypass paths.",
    "readme": "curriculum/advanced/23-enterprise-mcp-security-architecture/README.md",
    "lab": "curriculum/advanced/23-enterprise-mcp-security-architecture/lab.py",
    "notebook": "curriculum/advanced/23-enterprise-mcp-security-architecture/enterprise_architecture.ipynb"
  },
  {
    "id": "advanced-24",
    "level": "Advanced",
    "step": "24",
    "title": "MCP Identity and Non-Human Identity Governance",
    "summary": "Govern hosts, clients, servers, agents, gateways, CI jobs, and service accounts as non-human identities; assign ownership; bind each identity to audience and least privilege; automate short-lived issuance/rotation/revocation; and detect orphaned or overprivileged identities.",
    "readme": "curriculum/advanced/24-mcp-identity-non-human-identity-governance/README.md",
    "lab": "curriculum/advanced/24-mcp-identity-non-human-identity-governance/lab.py",
    "notebook": "curriculum/advanced/24-mcp-identity-non-human-identity-governance/nonhuman_identity.ipynb"
  },
  {
    "id": "advanced-25",
    "level": "Advanced",
    "step": "25",
    "title": "MCP Security Governance and Risk Management",
    "summary": "Translate MCP threats into owned risks; connect controls to tests, telemetry, incidents, and evidence; operate exceptions and residual-risk decisions; and establish review triggers for system, vendor, model, capability, identity, and deployment changes.",
    "readme": "curriculum/advanced/25-mcp-security-governance-risk-management/README.md",
    "lab": "curriculum/advanced/25-mcp-security-governance-risk-management/lab.py",
    "notebook": "curriculum/advanced/25-mcp-security-governance-risk-management/governance_risk.ipynb"
  },
  {
    "id": "advanced-26",
    "level": "Advanced",
    "step": "26",
    "title": "MCP Supply-Chain Risk Management",
    "summary": "Manage server, SDK, connector, model, package, registry, build, and vendor risk as a portfolio; tier suppliers by impact; require provenance/SBOM/vulnerability evidence and accountable ownership; and define onboarding, monitoring, exception, revocation, and offboarding decisions.",
    "readme": "curriculum/advanced/26-mcp-supply-chain-risk-management/README.md",
    "lab": "curriculum/advanced/26-mcp-supply-chain-risk-management/lab.py",
    "notebook": "curriculum/advanced/26-mcp-supply-chain-risk-management/supply_chain_risk.ipynb"
  },
  {
    "id": "advanced-27",
    "level": "Advanced",
    "step": "27",
    "title": "MCP Security Observability and SOC Integration",
    "summary": "Normalize MCP telemetry for SOC workflows; retain server digest, trace, tenant/principal scope, capability/action, destination, policy decision, and severity; enrich/dedupe alerts; and preserve a path from alert to containment and recovery evidence.",
    "readme": "curriculum/advanced/27-mcp-security-observability-soc-integration/README.md",
    "lab": "curriculum/advanced/27-mcp-security-observability-soc-integration/lab.py",
    "notebook": "curriculum/advanced/27-mcp-security-observability-soc-integration/soc_integration.ipynb"
  },
  {
    "id": "advanced-28",
    "level": "Advanced",
    "step": "28",
    "title": "MCP Threat Hunting and Runtime Anomaly Detection",
    "summary": "Form evidence-based MCP hunt hypotheses; query normalized traces for unexpected artifact, capability, identity, tenant, destination, approval, and denial patterns; distinguish a signal from a verdict; and route findings to triage, containment, and regression tests.",
    "readme": "curriculum/advanced/28-mcp-threat-hunting-runtime-anomaly-detection/README.md",
    "lab": "curriculum/advanced/28-mcp-threat-hunting-runtime-anomaly-detection/lab.py",
    "notebook": "curriculum/advanced/28-mcp-threat-hunting-runtime-anomaly-detection/threat_hunting.ipynb"
  },
  {
    "id": "advanced-29",
    "level": "Advanced",
    "step": "29",
    "title": "MCP Security Architecture Review Workshop",
    "summary": "Conduct a structured review of an MCP platform or integration; trace design claims to threat model, identity, policy, provenance, isolation, telemetry, recovery, owner, and test evidence; and produce prioritized remediation with explicit residual risk.",
    "readme": "curriculum/advanced/29-mcp-security-architecture-review-workshop/README.md",
    "lab": "curriculum/advanced/29-mcp-security-architecture-review-workshop/lab.py",
    "notebook": "curriculum/advanced/29-mcp-security-architecture-review-workshop/architecture_review.ipynb"
  }
];
