const REPO='https://github.com/mahsa-teimourikia/mcp-security';
const LESSONS=[
{level:'beginner',step:1,title:'MCP boundaries and manifests',summary:'Inventory servers, tools, resources, schemas, owners, and destinations.',detail:'Treat every server as an untrusted extension. Review tool names and schemas before a model can call them.',material:`${REPO}/blob/main/docs/01-mcp-architecture-and-threat-model.md`,lab:`${REPO}/blob/main/labs/beginner/01_manifest_inventory.py`,run:'python3 labs/beginner/01_manifest_inventory.py',q:['A tool description is…',['an authorization grant','untrusted metadata to review','a signed package'],1,'Descriptions are input, not permission.']},
{level:'beginner',step:2,title:'Tool schemas and safe boundaries',summary:'Validate names, arguments, tenant constraints, and side effects outside the model.',detail:'Allow-list typed tools, reject arbitrary shell/URL operations, and enforce resource boundaries in application code.',material:`${REPO}/blob/main/docs/04-runtime-isolation-and-tool-safety.md`,lab:`${REPO}/blob/main/labs/beginner/02_tool_boundary.py`,run:'python3 labs/beginner/02_tool_boundary.py',q:['Where should tenant checks live?',['Only in a prompt','At the API/tool boundary','Only in the UI'],1,'The enforcement point must be outside the model.']},
{level:'intermediate',step:3,title:'Provenance, SBOMs, and release gates',summary:'Pin digests, verify signatures, and reject unresolved findings.',detail:'Use signed artifacts, lockfiles, SBOMs, and vulnerability scanning to make a server release reproducible and reviewable.',material:`${REPO}/blob/main/docs/03-supply-chain-provenance-and-dependencies.md`,lab:`${REPO}/blob/main/labs/intermediate/01_provenance_gate.py`,run:'python3 labs/intermediate/01_provenance_gate.py',notebook:`${REPO}/blob/main/labs/notebooks/02_provenance_gate.ipynb`,q:['What does a digest pin provide?',['mutable latest behavior','an immutable artifact reference','model confidence'],1,'A digest identifies the exact bytes under review.']},
{level:'intermediate',step:4,title:'OAuth and egress controls',summary:'Bind credentials to audiences and block SSRF/private destinations.',detail:'Never forward a bearer token across resources. Combine audience-bound authorization with HTTPS allow-lists and network controls.',material:`${REPO}/blob/main/docs/02-protocol-authentication-and-authorization.md`,lab:`${REPO}/blob/main/labs/intermediate/02_egress_policy.py`,run:'python3 labs/intermediate/02_egress_policy.py',q:['Which destination should be blocked?',['approved HTTPS API','cloud metadata IP','approved ticket API'],1,'Metadata endpoints are a common SSRF target.']},
{level:'advanced',step:5,title:'Delegation across MCP and A2A',summary:'Pass typed, bounded authority across agent-protocol hops.',detail:'Authenticate peers and authorize each task with audience, action, lifetime, and depth constraints.',material:`${REPO}/blob/main/docs/02-protocol-authentication-and-authorization.md`,lab:`${REPO}/blob/main/labs/advanced/01_delegation_contract.py`,run:'python3 labs/advanced/01_delegation_contract.py',q:['What prevents delegation escalation?',['Scope intersection and depth limits','Forwarding bearer tokens','Unbounded retries'],0,'Delegation can only narrow authority.']},
{level:'advanced',step:6,title:'Incident response and rollback',summary:'Revoke a compromised server, preserve evidence, and recover safely.',detail:'Use a kill switch, audit traces, known-good digests, and a tested rollback path when a dependency or server is compromised.',material:`${REPO}/blob/main/docs/05-incident-response-and-operations.md`,lab:`${REPO}/blob/main/labs/advanced/02_incident_response.py`,run:'python3 labs/advanced/02_incident_response.py',q:['First containment action for a malicious server?',['Disable/revoke it','Give it more scopes','Wait for a model update'],0,'Disable the server and preserve affected events.']},
{level:'advanced',step:7,title:'Secure-server capstone',summary:'Combine inventory, policy, provenance, isolation, and recovery gates.',detail:'Implement the support-server scenario, run the adversarial cases, and document evidence for each release gate.',material:`${REPO}/blob/main/docs/07-mcp-capstone.md`,lab:`${REPO}/blob/main/labs/capstone_secure_server.py`,run:'python3 labs/capstone_secure_server.py',q:['What proves capstone readiness?',['A tested allow/deny policy and rollback evidence','A model-generated claim','An unpinned latest image'],0,'Readiness requires executable controls and recovery evidence.']},
{level:'advanced',step:8,title:'Operate and compare protocols',summary:'Use the operator checklist to prepare for incidents and compare MCP, A2A, and tool calling.',detail:'Complete the threat-model worksheet, operator checklist, and protocol comparison before production release.',material:`${REPO}/blob/main/docs/09-operator-checklist.md`,lab:`${REPO}/blob/main/docs/10-protocol-comparison.md`,run:'Review docs/08-threat-model-worksheet.md and docs/09-operator-checklist.md',q:['What is the first incident action for a malicious server?',['Disable/revoke and preserve evidence','Grant more access','Delete all logs'],0,'Contain quickly while preserving evidence for investigation.']}
];
