const REPO='https://github.com/mahsa-teimourikia/mcp-security';
const LESSONS=[
{level:'beginner',step:1,title:'MCP boundaries and manifests',summary:'Inventory servers, tools, resources, schemas, owners, and destinations.',detail:'Treat every server as an untrusted extension. Review tool names and schemas before a model can call them.',material:`${REPO}/blob/main/docs/mcp-supply-chain-security.md#mcp-trust-boundaries`,lab:`${REPO}/blob/main/labs/beginner/01_manifest_inventory.py`,run:'python3 labs/beginner/01_manifest_inventory.py',q:['A tool description is…',['an authorization grant','untrusted metadata to review','a signed package'],1,'Descriptions are input, not permission.']},
{level:'beginner',step:2,title:'Tool schemas and safe boundaries',summary:'Validate names, arguments, tenant constraints, and side effects outside the model.',detail:'Allow-list typed tools, reject arbitrary shell/URL operations, and enforce resource boundaries in application code.',material:`${REPO}/blob/main/docs/mcp-supply-chain-security.md#tool-calling-controls`,lab:`${REPO}/blob/main/labs/beginner/02_tool_boundary.py`,run:'python3 labs/beginner/02_tool_boundary.py',q:['Where should tenant checks live?',['Only in a prompt','At the API/tool boundary','Only in the UI'],1,'The enforcement point must be outside the model.']},
{level:'intermediate',step:3,title:'Provenance, SBOMs, and release gates',summary:'Pin digests, verify signatures, and reject unresolved findings.',detail:'Use signed artifacts, lockfiles, SBOMs, and vulnerability scanning to make a server release reproducible and reviewable.',material:`${REPO}/blob/main/docs/mcp-supply-chain-security.md#supply-chain-lifecycle`,lab:`${REPO}/blob/main/labs/intermediate/01_provenance_gate.py`,run:'python3 labs/intermediate/01_provenance_gate.py',notebook:`${REPO}/blob/main/labs/notebooks/02_provenance_gate.ipynb`,q:['What does a digest pin provide?',['mutable latest behavior','an immutable artifact reference','model confidence'],1,'A digest identifies the exact bytes under review.']},
{level:'intermediate',step:4,title:'OAuth and egress controls',summary:'Bind credentials to audiences and block SSRF/private destinations.',detail:'Never forward a bearer token across resources. Combine audience-bound authorization with HTTPS allow-lists and network controls.',material:`${REPO}/blob/main/docs/mcp-supply-chain-security.md#protocol-and-identity-considerations`,lab:`${REPO}/blob/main/labs/intermediate/02_egress_policy.py`,run:'python3 labs/intermediate/02_egress_policy.py',q:['Which destination should be blocked?',['approved HTTPS API','cloud metadata IP','approved ticket API'],1,'Metadata endpoints are a common SSRF target.']},
{level:'advanced',step:5,title:'Delegation across MCP and A2A',summary:'Pass typed, bounded authority across agent-protocol hops.',detail:'Authenticate peers and authorize each task with audience, action, lifetime, and depth constraints.',material:`${REPO}/blob/main/docs/mcp-supply-chain-security.md#protocol-and-identity-considerations`,lab:`${REPO}/blob/main/labs/advanced/01_delegation_contract.py`,run:'python3 labs/advanced/01_delegation_contract.py',q:['What prevents delegation escalation?',['Scope intersection and depth limits','Forwarding bearer tokens','Unbounded retries'],0,'Delegation can only narrow authority.']},
{level:'advanced',step:6,title:'Incident response and rollback',summary:'Revoke a compromised server, preserve evidence, and recover safely.',detail:'Use a kill switch, audit traces, known-good digests, and a tested rollback path when a dependency or server is compromised.',material:`${REPO}/blob/main/docs/mcp-supply-chain-security.md#threat-scenarios`,lab:`${REPO}/blob/main/labs/advanced/02_incident_response.py`,run:'python3 labs/advanced/02_incident_response.py',q:['First containment action for a malicious server?',['Disable/revoke it','Give it more scopes','Wait for a model update'],0,'Disable the server and preserve affected events.']}
];
