import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const trackNames = { beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" };
const lessons = [];

function firstParagraph(markdown) {
  const withoutHeading = markdown.replace(/^# .+\n+/, "");
  return withoutHeading
    .split(/\n\s*\n/)
    .map((block) => block.replace(/\s+/g, " ").trim())
    .find((block) => block && !block.startsWith("#") && !block.startsWith("```"))
    ?.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[*_`]/g, "") ?? "Open the lesson for theory, failure modes, and exercises.";
}

for (const [track, level] of Object.entries(trackNames)) {
  const trackDir = resolve(root, "curriculum", track);
  const entries = (await readdir(trackDir, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory() && /^\d{2}-/.test(entry.name))
    .sort((a, b) => a.name.localeCompare(b.name));

  for (const entry of entries) {
    const topicDir = resolve(trackDir, entry.name);
    const files = await readdir(topicDir);
    const notebook = files.find((name) => name.endsWith(".ipynb"));
    if (!notebook || !files.includes("README.md") || !files.includes("lab.py")) {
      throw new Error(`Incomplete lesson directory: ${relative(root, topicDir)}`);
    }
    const markdown = await readFile(resolve(topicDir, "README.md"), "utf8");
    const title = markdown.match(/^# (.+)$/m)?.[1];
    if (!title) throw new Error(`Missing H1: ${relative(root, topicDir)}/README.md`);
    const step = entry.name.slice(0, 2);
    const base = relative(root, topicDir).split("\\").join("/");
    lessons.push({
      id: `${track}-${step}`,
      level,
      step,
      title,
      summary: firstParagraph(markdown),
      readme: `${base}/README.md`,
      lab: `${base}/lab.py`,
      notebook: `${base}/${notebook}`,
    });
  }
}

const output = `// Generated by app/scripts/generate-lessons.mjs. Do not edit manually.\n` +
  `export type Level = "Beginner" | "Intermediate" | "Advanced";\n` +
  `export type Lesson = { id: string; level: Level; step: string; title: string; summary: string; readme: string; lab: string; notebook: string };\n` +
  `export const lessons: Lesson[] = ${JSON.stringify(lessons, null, 2)};\n`;

await writeFile(resolve(root, "app/generated-lessons.ts"), output);
console.log(`Generated ${lessons.length} Learning Hub lessons.`);
